import type { DisplayElements } from '@busy-app/busy-lib';

/*
 * Paint-by-number icons. Each icon carries a `pixels` grid of palette indices
 * and a `colors` lookup from index to RGBA hex. Index 0 is transparent
 * (`#00000000`) by convention; `render_icon` skips any fully transparent color.
 *
 * Generated by tmp/gen-icons.mjs from source PNGs, with RGB snapped to the
 * nearest 32 and alpha flattened to on/off.
 */

export type icon = {
  width: number;
  height: number;
  colors: Record<number, string>;
  pixels: number[][];
};

const is_transparent = (color: string): boolean => color.slice(-2) === '00';

export type render_opts = {
  x: number;
  y: number;
  timeout: number;
  id_prefix: string;
  display?: 'front' | 'back';
};

export function render_icon(
  icon: icon,
  opts: render_opts,
): DisplayElements['elements'] {
  const elements: DisplayElements['elements'] = [];
  const display = opts.display ?? 'front';
  let n = 0;
  for (let y = 0; y < icon.pixels.length; y++) {
    const row = icon.pixels[y];
    if (!row) continue;
    let x = 0;
    while (x < row.length) {
      const index = row[x];
      const color = index === undefined ? undefined : icon.colors[index];
      if (color === undefined || is_transparent(color)) {
        x++;
        continue;
      }
      let run = 1;
      while (x + run < row.length && row[x + run] === index) run++;
      elements.push({
        id: `${opts.id_prefix}_${n++}`,
        type: 'rectangle',
        x: opts.x + x,
        y: opts.y + y,
        display,
        width: run,
        height: 1,
        fill: 'solid',
        fill_colors: [color],
        border_width: 0,
        border_color: '#00000000',
        timeout: opts.timeout,
      });
      x += run;
    }
  }
  return elements;
}

export const cat: icon = {
  width: 16,
  height: 16,
  colors: {
    0: '#00000000',
    1: '#404040FF',
    2: '#E0A0A0FF',
    3: '#A0A0A0FF',
    4: '#806060FF',
    5: '#40C0FFFF',
    6: '#000000FF',
    7: '#808080FF',
  },
  pixels: [
    [0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 2, 3, 1, 1, 1, 1, 1, 3, 2, 1, 0, 0, 0, 0],
    [0, 1, 2, 2, 4, 3, 4, 3, 4, 2, 2, 1, 0, 0, 0, 0],
    [0, 1, 3, 3, 4, 3, 3, 3, 4, 3, 3, 1, 0, 0, 0, 0],
    [0, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 0, 0, 0, 0],
    [0, 1, 4, 3, 5, 3, 3, 3, 5, 3, 4, 1, 0, 0, 0, 0],
    [4, 4, 3, 3, 6, 3, 6, 3, 6, 3, 3, 4, 4, 0, 0, 0],
    [0, 1, 4, 3, 3, 3, 3, 3, 3, 3, 4, 1, 0, 0, 0, 0],
    [4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 0, 0, 0],
    [0, 0, 1, 1, 3, 3, 3, 3, 3, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 3, 3, 3, 1, 0, 0, 0, 1, 1, 1, 0],
    [0, 0, 0, 0, 1, 3, 3, 3, 4, 1, 0, 1, 4, 4, 4, 1],
    [0, 0, 0, 0, 1, 3, 7, 3, 3, 4, 1, 3, 3, 4, 3, 1],
    [0, 0, 0, 0, 1, 7, 4, 7, 3, 3, 4, 3, 1, 1, 1, 0],
    [0, 0, 0, 0, 1, 3, 1, 3, 1, 3, 1, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
  ],
};

/*
 * Per-pet cat themes. A theme is a partial override of the cat palette, keyed by
 * (normalized) pet name; unspecified indices fall back to `cat.colors`.
 *
 * Cat palette slots:
 *   1 outline · 2 nose · 3 fur (light) · 4 shading · 5 eyes · 6 pupil · 7 fur (mid)
 * (0 is transparent and should not be themed.)
 */
export type icon_theme = Partial<Record<number, string>>;

export const cat_themes: Record<string, icon_theme> = {
  winky: {
    1: '#804000FF',
    2: '#E0E0C0FF',
    3: '#C08060FF',
    4: '#C06020FF',
    7: '#C08040FF',
  },
};

const normalize_pet_name = (name: string): string => name.trim().toLowerCase();

export function apply_theme(base: icon, theme: icon_theme | undefined): icon {
  if (theme === undefined) return base;
  const colors: Record<number, string> = { ...base.colors };
  for (const [index, color] of Object.entries(theme)) {
    if (color !== undefined) colors[Number(index)] = color;
  }
  return { ...base, colors };
}

export function cat_icon(pet_name: string | null): icon {
  const theme =
    pet_name === null ? undefined : cat_themes[normalize_pet_name(pet_name)];
  return apply_theme(cat, theme);
}

export const spotify: icon = {
  width: 16,
  height: 16,
  colors: {
    0: '#FFFFFFFF',
    1: '#E0FFFFFF',
    2: '#C0E0C0FF',
    3: '#40C040FF',
    4: '#A0C0A0FF',
    5: '#80C080FF',
    6: '#80E060FF',
    7: '#A0FF60FF',
    8: '#80E040FF',
    9: '#80E020FF',
    10: '#60E040FF',
    11: '#60C040FF',
    12: '#60C080FF',
    13: '#40A020FF',
    14: '#202000FF',
    15: '#000000FF',
    16: '#C0C0C0FF',
    17: '#40A040FF',
    18: '#60A020FF',
    19: '#208060FF',
    20: '#204020FF',
    21: '#206020FF',
    22: '#408020FF',
    23: '#206040FF',
    24: '#204000FF',
    25: '#002000FF',
    26: '#206060FF',
    27: '#208040FF',
    28: '#E0E0FFFF',
    29: '#608080FF',
    30: '#20A040FF',
    31: '#80A0A0FF',
    32: '#A0C0C0FF',
  },
  pixels: [
    [0, 0, 0, 0, 1, 2, 3, 3, 3, 3, 2, 1, 0, 0, 0, 0],
    [0, 0, 0, 4, 5, 6, 7, 7, 7, 7, 6, 5, 4, 0, 0, 0],
    [0, 0, 2, 8, 9, 8, 8, 8, 8, 8, 8, 9, 8, 2, 0, 0],
    [0, 4, 8, 9, 10, 11, 11, 11, 11, 11, 11, 10, 9, 8, 4, 0],
    [1, 12, 8, 11, 13, 14, 15, 15, 15, 15, 14, 13, 11, 8, 12, 1],
    [16, 17, 18, 14, 15, 15, 13, 13, 13, 13, 15, 15, 14, 18, 17, 16],
    [19, 3, 11, 20, 21, 11, 22, 22, 22, 22, 11, 21, 20, 11, 3, 19],
    [23, 3, 11, 11, 13, 20, 15, 15, 15, 15, 20, 13, 11, 11, 3, 23],
    [23, 3, 11, 24, 25, 20, 22, 11, 11, 22, 20, 25, 24, 11, 3, 23],
    [26, 17, 11, 13, 13, 11, 13, 20, 20, 13, 11, 13, 13, 11, 17, 26],
    [16, 27, 11, 11, 13, 25, 15, 14, 14, 15, 25, 13, 11, 11, 27, 16],
    [28, 29, 30, 3, 15, 22, 18, 11, 11, 18, 22, 15, 11, 30, 29, 28],
    [0, 31, 27, 30, 30, 3, 11, 11, 11, 11, 3, 30, 30, 27, 31, 0],
    [0, 0, 32, 27, 30, 30, 30, 30, 30, 30, 30, 30, 27, 32, 0, 0],
    [0, 0, 0, 31, 29, 27, 30, 30, 30, 30, 27, 29, 31, 0, 0, 0],
    [0, 0, 0, 0, 28, 16, 26, 23, 23, 26, 16, 28, 0, 0, 0, 0],
  ],
};
